### ISSUE TITLE
Calling install-repl fails on SBCL and CCL

### ISSUE THREAD

**Issue by mindbound** [sharplispers/linedit#2]
Invoking e.g. `(linedit:install-repl :wrap-current t :eof-quits t)` on SBCL causes the following error:
```debugger invoked on a SIMPLE-ERROR in thread
#<THREAD "main thread" RUNNING {10005505B3}>:
  Invalid file format

Type HELP for debugger help, or (SB-EXT:EXIT) to exit from SBCL.

restarts (invokable by number or by possibly-abbreviated name):
  0: [ABORT] Exit debugger, returning to top level.

(TERMINFO::LOAD-TERMINFO "xterm-256color")
   source: (ERROR "Invalid file format")
```
The same call has comparable results on CCL. I'm using Arch Linux 4.17.3-1 x86_64, SBCL 1.4.8, CCL 1.12-dev. `TERM` is set to `xterm-256color`. Thanks in advance.

**Comment by khirbat** [comment]
More details here https://github.com/npatrick04/terminfo/issues/3

**Comment by khirbat** [comment]
Should be fixed in https://github.com/npatrick04/terminfo/issues/3. Use quicklisp 2018-08-31 or later.
